version: 2

updates:
  # .NET dependencies (NuGet)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "mandant10"
    labels:
      - "dependencies"
      - "dotnet"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Grupuj minor i patch updates
    groups:
      dotnet-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Ignoruj niektóre pakiety jeśli potrzeba
    ignore:
      # Przykład: ignoruj major updates pewnych pakietów
      # - dependency-name: "Microsoft.AspNetCore.*"
      #   update-types: ["version-update:semver-major"]

  # Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "mandant10"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      python-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "first-monday"
    open-pull-requests-limit: 3
    reviewers:
      - "mandant10"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    groups:
      github-actions-all:
        patterns:
          - "*"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 3
    reviewers:
      - "mandant10"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
