name: Test MCP Server

on:
  push:
    branches: [ main ]
    paths:
      - 'mcp_server_minesweeper.py'
      - 'test_mcp_*.py'
  pull_request:
    branches: [ main ]

jobs:
  test-mcp:
    name: Test MCP Server
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install MCP dependencies
      run: |
        pip install --upgrade pip
        pip install mcp httpx
        
    - name: Setup .NET (for backend API)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Start backend API
      run: |
        dotnet build --configuration Release
        nohup dotnet run --no-build --configuration Release > api.log 2>&1 &
        sleep 5
        
    - name: Test API is running
      run: |
        curl -f http://localhost:5022/api/scores?limit=1 || (cat api.log && exit 1)
        
    - name: Run MCP tests
      run: |
        python3 test_mcp_interactive.py
        
    - name: Show API logs on failure
      if: failure()
      run: cat api.log
